# -*- coding: utf-8 -*-
"""automate_Muhammad Ali Maruf

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G1B-YDyLUvBp4NqTK0RsMOcjVi9ltx9T

# Membuat File Automate

1. Import Library
"""

# Membuat file otomatis

# Import Library
import pandas as pd
import numpy as np
import os
import joblib
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

"""2. Membuat path"""

import os

# Tentukan nama folder
ARTIFACT_DIR = "artifacts"

# Tentukan path file di dalam folder tersebut
data_path = os.path.join(ARTIFACT_DIR, "social_media_mental_health_preprocessing.csv")
model_path = os.path.join(ARTIFACT_DIR, "model.pkl")

# Buat folder artifacts jika belum ada
os.makedirs(ARTIFACT_DIR, exist_ok=True)

# Cetak informasi untuk memastikan
print(f"Direktori artifacts: {os.path.abspath(ARTIFACT_DIR)}")
print(f"Path data: {data_path}")
print(f"Path model: {model_path}")

ARTIFACT_DIR = "artifacts"
data_path = os.path.join(ARTIFACT_DIR, "social_media_mental_health_preprocessing.csv")
model_path = os.path.join(ARTIFACT_DIR, "model.pkl")
os.makedirs(ARTIFACT_DIR, exist_ok=True)

"""3.Loading dataset yang sudah dilakukan preprocessing"""

df = pd.read_csv(data_path)
df.head()

"""4. Membangun Model"""

# Memisahkan fitur dan target
X = df.drop(columns=['mental_state'])
y = df['mental_state']

# Split data train dan test
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
    )

# Membangun model logistic regression multiclass
model = LogisticRegression(
    multi_class='multinomial',
    solver='lbfgs',
    max_iter=1000
    )
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print("\nModel Evaluation")
print("----------------")
print(f"Accuracy: {accuracy:.4f}")
print(report)

# Menyimpan model
joblib.dump(model, model_path)

print("\nAutomate selesai.")