# -*- coding: utf-8 -*-
"""modelling_tunning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bl-2sODXWV1ws-CHQnq7DC0Wy5-_zcvt

# Membangun Model Machine Learning Skilled

1. Import Library
"""

# Commented out IPython magic to ensure Python compatibility.
# Kriteria 2 skilled

# Import Library
import dagshub
!pip install mlflow
import pandas as pd
import numpy as np
import os
import joblib
import matplotlib.pyplot as plt
import seaborn as sns
import mlflow
import mlflow.sklearn
import shutil
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, f1_score, precision_score, recall_score
from sklearn.ensemble import RandomForestClassifier
# %pip install -q dagshub mlflow
!pip install mlflow pyngrok -q
from pyngrok import ngrok
!pip install mlflow dagshub scikit-learn

"""2. Membuat path"""

dagshub.init(
    repo_owner="alimaruf.jpn",
    repo_name="Eksperimen_SML_Muhammad-Ali",
    mlflow=True
)

print(mlflow.get_tracking_uri())

# Tentukan nama folder
ARTIFACT_DIR = "artifacts"

# Tentukan path file di dalam folder tersebut
data_path = os.path.join(ARTIFACT_DIR, "social_media_mental_health_preprocessing.csv")

# Buat folder artifacts jika belum ada
os.makedirs(ARTIFACT_DIR, exist_ok=True)
experiment_name = "mental_health_classification_skilled"

# Cetak informasi untuk memastikan
print(f"Direktori artifacts: {os.path.abspath(ARTIFACT_DIR)}")
print(f"Path data: {data_path}")

# Set MLflow

mlflow.set_experiment(experiment_name)

"""3.Loading dataset yang sudah dilakukan preprocessing"""

if not os.path.exists(data_path):
    print(f"File data tidak ditemukan di {data_path}")
df = pd.read_csv(data_path)
df.head()

"""4. Membangun Model"""

# Memisahkan fitur dan target
X = df.drop(columns=['mental_state'])
y = df['mental_state']

# Split data train dan test
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
    )

# Melihat dimensi fitur dan target
print("Dimensi fitur")
print(f"X_train: {X_train.shape}")
print(f"X_test: {X_test.shape}")

# Tunning hyperparameter
param_grid = {
    'n_estimators': [100,250],
    'max_depth': [10,20,30],
    'min_samples_split': [2,5,10],
    'min_samples_leaf': [1,3],
}

random_forest_model = RandomForestClassifier(random_state=42)
grid_search = GridSearchCV(estimator=random_forest_model, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)
model = grid_search.best_estimator_

# Evaluate
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')

# Cetak
print(f"Akurasi: {accuracy}")
print(f"Presisi: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")

# Artifak
cm= confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',cbar=False)
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
confusion_matrix_path = os.path.join(ARTIFACT_DIR, "confusion_matrix.png")
plt.savefig(confusion_matrix_path, dpi=150, bbox_inches='tight')

# Penyimpanan Model
file_dir = 'mlflow_artifact'
if os.path.exists(file_dir):
    shutil.rmtree(file_dir)
os.makedirs(file_dir)

mlflow.sklearn.save_model(sk_model=model, path=os.path.join(file_dir, 'model'))
shutil.copy(confusion_matrix_path,os.path.join(file_dir, 'confusion_matrix.png'))

# Upload
dagshub.init(repo_owner='alimaruf.jpn',
             repo_name='Eksperimen_SML_Muhammad-Ali',
             mlflow=True)
with mlflow.start_run(run_name='random_forest_tunning') as run:
      mlflow.log_params(grid_search.best_params_)
      mlflow.log_metric("accuracy", accuracy)
      mlflow.log_metric("precision", precision)
      mlflow.log_metric("recall", recall)
      mlflow.log_metric("f1", f1)
      mlflow.log_artifact(confusion_matrix_path)
      mlflow.sklearn.log_model(
        sk_model=grid_search.best_estimator_,
        artifact_path="model",
        input_example=X_test[:1])
      mlflow.log_artifact(confusion_matrix_path)

print(mlflow.get_tracking_uri())